sass:
  style: compressed
author:
  name: "Yvan Volochine"
title: Trema Inc.
email: contact@trema.io
description: >- # this means to ignore newlines until "baseurl:"
  Multi artist, music, performance, code, clown, noise music, avant-guarde
  music, avant-guarde performance, psycho acoustics, supercollider
baseurl: ""
url: ""
github_username: gusano

# Build settings
markdown: kramdown
plugins:
  - jekyll-assets

assets:
  compression: true

exclude:
   - Gemfile.lock
   - vendor/bundle/
